name: Build Android APK

on:
  workflow_dispatch:

env:
  VCPKG_COMMIT_ID: 2023.04.15

jobs:
  build-android:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake curl git g++ libclang-dev \
               libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
               libpulse-dev libxcb-randr0-dev libxcb-shape0-dev \
               libxcb-xfixes0-dev libxdo-dev libxfixes-dev nasm ninja-build \
               openjdk-17-jdk-headless pkg-config

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.3

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27b
          add-to-path: true

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Install tools
        run: |
          cargo install cargo-ndk
          cargo install cargo-expand --version 1.0.95 --locked
          cargo install flutter_rust_bridge_codegen --version 1.80.1 --features "uuid" --locked

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg /opt/vcpkg
          cd /opt/vcpkg
          git checkout $VCPKG_COMMIT_ID
          ./bootstrap-vcpkg.sh
          ./vcpkg install libvpx libyuv opus aom ffmpeg --triplet arm64-android
          echo "VCPKG_ROOT=/opt/vcpkg" >> $GITHUB_ENV

      - name: Generate bridge code
        run: |
          cd flutter && sed -i 's/extended_text: 14.0.0/extended_text: 13.0.0/g' pubspec.yaml && flutter pub get && cd ..
          flutter_rust_bridge_codegen --rust-input ./src/flutter_ffi.rs \
            --dart-output ./flutter/lib/generated_bridge.dart \
            --c-output ./flutter/macos/Runner/bridge_generated.h
          cp ./flutter/macos/Runner/bridge_generated.h ./flutter/ios/Runner/bridge_generated.h

      - name: Build native library
        run: bash flutter/ndk_arm64.sh

      - name: Build APK
        run: |
          cd flutter
          flutter build apk --release --target-platform android-arm64

      - uses: actions/upload-artifact@v4
        with:
          name: rustdesk-custom.apk
          path: flutter/build/app/outputs/flutter-apk/app-release.apk
